In [1]:
import pandas as pd
from sqlalchemy import create_engine

In [2]:
engine = create_engine(
    "postgresql+psycopg2://postgres:postgres@localhost:5432/healthcare_dw"
)

In [3]:
query = """
SELECT COUNT(*) AS total_records
FROM fact_patient_visit;
"""

pd.read_sql(query, engine)

   total_records
0            984

In [ ]:
# Pull KPI data
kpi_query = """
SELECT
    COUNT(*) AS total_visits,
    SUM(cost) AS total_cost,
    AVG(cost) AS avg_cost,
    AVG(length_of_stay) AS avg_length_of_stay,
    AVG(satisfaction) AS avg_satisfaction
FROM fact_patient_visit;
"""

kpi_df = pd.read_sql(kpi_query, engine)
kpi_df

   total_visits  total_cost     avg_cost  avg_length_of_stay  avg_satisfaction
0           984   8233600.0  8367.479675           37.663618          3.598577

In [5]:
# Export Tableau-Ready Dataset
tableau_query = """
SELECT
    fpv.visit_key,
    dp.patient_id,
    dp.age,
    dp.gender,
    dc.condition_name,
    dpr.procedure_name,
    dr.readmission_status,
    doo.outcome_status,
    fpv.cost,
    fpv.length_of_stay,
    fpv.satisfaction
FROM fact_patient_visit fpv
JOIN dim_patient dp
    ON fpv.patient_key = dp.patient_key
JOIN dim_condition dc
    ON fpv.condition_key = dc.condition_key
JOIN dim_procedure dpr
    ON fpv.procedure_key = dpr.procedure_key
JOIN dim_readmission dr
    ON fpv.readmission_key = dr.readmission_key
JOIN dim_outcome doo
    ON fpv.outcome_key = doo.outcome_key;
"""

tableau_df = pd.read_sql(tableau_query, engine)
tableau_df.head()

,visit_key,patient_id,age,gender,condition_name,procedure_name,readmission_status,outcome_status,cost,length_of_stay,satisfaction
0,1,1,45,Female,Heart Disease,Angioplasty,No,Recovered,15000.0,5,4
1,2,2,60,Male,Diabetes,Insulin Therapy,Yes,Stable,2000.0,3,3
2,3,3,32,Female,Fractured Arm,X-Ray and Splint,No,Recovered,500.0,1,5
3,4,4,75,Male,Stroke,CT Scan and Medication,Yes,Stable,10000.0,7,2
4,5,5,50,Female,Cancer,Surgery and Chemotherapy,No,Recovered,25000.0,10,4

In [6]:
# Save
import os

os.makedirs("../data/processed", exist_ok=True)

tableau_df.to_csv(
    "../data/processed/healthcare_tableau_dataset.csv",
    index=False
)

In [7]:
# Export KPI Summary
kpi_df.to_csv(
    "../data/processed/healthcare_kpi_summary.csv",
    index=False
)